swagger: "2.0"
info:
  description: "This is an application to allow clients to auto request service"
  version: "1.0.0"
  title: "Swagger Robo Lunch"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "at.sampaio@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v1"
tags:
  - name: "account"
    description: "Account created for clients request lunch"
    externalDocs:
      description: "Find out more"
      url: "http://swagger.io"
  - name: "menuitens"
    description: "Itens to be requested by de user"
  - name: "customer"
    description: "Customer users"
schemes:
  - "https"
  - "http"
paths:
  /account:
    put:
      tags:
        - "account"
      summary: "Create new account"
      description: ""
      operationId: "addPet"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Pet object that needs to be added to the store"
          required: true
      responses:
        "405":
          description: "Invalid input"
      security:
        - petstore_auth:
            - "write:pets"
            - "read:pets"
    put:
      tags:
        - "pet"
      summary: "Update an existing pet"
      description: ""
      operationId: "updatePet"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Pet object that needs to be added to the store"
          required: true
          schema:
            $ref: "#/definitions/Pet"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"
      security:
        - petstore_auth:
            - "write:pets"
            - "read:pets"
definitions:
  Order:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      petId:
        type: "integer"
        format: "int64"
      quantity:
        type: "integer"
        format: "int32"
      shipDate:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        description: "Order Status"
        enum:
        - "placed"
        - "approved"
        - "delivered"
      complete:
        type: "boolean"
        default: false
    xml:
      name: "Order"
            
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
